const DECKS_MOCK = [
  {
    id: 1,
    name: "Toys Very Very Long Name",
    url: "/",
    tags: ["Children", "Games"],
    rating: 4.5,
    views: 43,
    cards: ["SSome card with long content to check how it will rednerSome card with long content to check how it will rednerSome card with long content to check how it will rednerome card with long content to check how it will redner", "Cards", "Car", "Ball", "Wheel", "LEGO", "Cards", "Car", "Ball", "Wheel", "LEGO", "Cards", "Car", "Ball", "Wheel", "LEGO", "Cards", "Car", "Ball", "Wheel", "LEGO", "Cards", "Car", "Ball", "Wheel", "LEGO", "Cards", "Car", "Ball", "Wheel", "LEGO"],
  },
  {
    id: 3333,
    name: "Films",
    url: "/",
    tags: ["Actors", "Games"],
    rating: 4.5,
    views: 43,
    cards: ["Matrix", "Westwood", "Inception", "Wicked Games", "Avatar"],
  },
  {
    id: 1231,
    name: "Actors",
    url: "/",
    tags: ["Films", "TV-shows"],
    rating: 4.5,
    views: 43,
    cards: ["Dicaprio", "Matt Damon", "Johny", "Wheel", "LEGO"],
  },
  {
    id: 20,
    name: "Flowers",
    url: "/",
    tags: ["auto"],
    rating: 4.0,
    views: 100,
    cards: ["Rose", "Cactus", "Cleo", "Green Rose", "Pink Rose"],
  },
  {
    id: 313,
    name: "Toys",
    url: "/",
    tags: ["Children", "Games"],
    rating: 4.5,
    views: 43,
    cards: ["Cards", "Car", "Ball", "Wheel", "LEGO"],
  },
  {
    id: 255,
    name: "Films",
    url: "/",
    tags: ["Actors", "Games"],
    rating: 4.5,
    views: 43,
    cards: ["Matrix", "Westwood", "Inception", "Wicked Games", "Avatar"],
  },
  {
    id: 212,
    name: "Actors",
    url: "/",
    tags: ["Films", "TV-shows"],
    rating: 4.5,
    views: 43,
    cards: ["Dicaprio", "Matt Damon", "Johny", "Wheel", "LEGO"],
  },
  {
    id: 112,
    name: "Flowers",
    url: "/",
    tags: ["auto"],
    rating: 4.0,
    views: 100,
    cards: ["Rose", "Cactus", "Cleo", "Green Rose", "Pink Rose"],
  },
  {
    id: 1243,
    name: "Toys",
    url: "/",
    tags: ["Children", "Games"],
    rating: 4.5,
    views: 43,
    cards: ["Cards", "Car", "Ball", "Wheel", "LEGO"],
  },
  {
    id: 243,
    name: "Films",
    url: "/",
    tags: ["Actors", "Games"],
    rating: 4.5,
    views: 43,
    cards: ["Matrix", "Westwood", "Inception", "Wicked Games", "Avatar"],
  },
  {
    id: 289,
    name: "Actors",
    url: "/",
    tags: ["Films", "TV-shows"],
    rating: 4.5,
    views: 43,
    cards: ["Dicaprio", "Matt Damon", "Johny", "Wheel", "LEGO"],
  },
  {
    id: 290,
    name: "Flowers",
    url: "/",
    tags: ["auto"],
    rating: 4.0,
    views: 100,
    cards: ["Rose", "Cactus", "Cleo", "Green Rose", "Pink Rose"],
  },
  {
    id: 240,
    url: "/",
    name: "Toys",
    tags: ["Children", "Games"],
    rating: 4.5,
    views: 43,
    cards: ["Cards", "Car", "Ball", "Wheel", "LEGO"],
  },
  {
    id: 230,
    name: "Toys",
    url: "/",
    tags: ["Children", "Games"],
    rating: 4.5,
    views: 43,
    cards: ["Cards", "Car", "Ball", "Wheel", "LEGO"],
  },
  {
    id: 39,
    name: "Films",
    url: "/",
    tags: ["Actors", "Games"],
    rating: 4.5,
    views: 43,
    cards: ["Matrix", "Westwood", "Inception", "Wicked Games", "Avatar"],
  },
  {
    id: 55,
    name: "Actors",
    url: "/",
    tags: ["Films", "TV-shows"],
    rating: 4.5,
    views: 43,
    cards: ["Dicaprio", "Matt Damon", "Johny", "Wheel", "LEGO"],
  },
  {
    id: 100,
    name: "Flowers",
    url: "/",
    tags: ["auto"],
    rating: 4.0,
    views: 100,
    cards: ["Rose", "Cactus", "Cleo", "Green Rose", "Pink Rose"],
  },
  {
    id: 898,
    name: "Toys",
    url: "/",
    tags: ["Children", "Games"],
    rating: 4.5,
    views: 43,
    cards: ["Cards", "Car", "Ball", "Wheel", "LEGO"],
  },
  {
    id: 3,
    name: "Films",
    url: "/",
    tags: ["Actors", "Games"],
    rating: 4.5,
    views: 43,
    cards: ["Matrix", "Westwood", "Inception", "Wicked Games", "Avatar"],
  },
  {
    id: 288,
    name: "Actors",
    url: "/",
    tags: ["Films", "TV-shows"],
    rating: 4.5,
    views: 43,
    cards: ["Dicaprio", "Matt Damon", "Johny", "Wheel", "LEGO"],
  },
  {
    id: 8,
    name: "Flowers",
    url: "/",
    tags: ["auto"],
    rating: 4.0,
    views: 100,
    cards: ["Rose", "Cactus", "Cleo", "Green Rose", "Pink Rose"],
  },
  {
    id: 2101,
    name: "Toys",
    url: "/",
    tags: ["Children", "Games"],
    rating: 4.5,
    views: 43,
    cards: ["Cards", "Car", "Ball", "Wheel", "LEGO"],
  },
  {
    id: 214,
    name: "Films",
    url: "/",
    tags: ["Actors", "Games"],
    rating: 4.5,
    views: 43,
    cards: ["Matrix", "Westwood", "Inception", "Wicked Games", "Avatar"],
  },
  {
    name: "Actors",
    id: 233,
    url: "/",
    tags: ["Films", "TV-shows"],
    rating: 4.5,
    views: 43,
    cards: ["Dicaprio", "Matt Damon", "Johny", "Wheel", "LEGO"],
  },
  {
    name: "Flowers",
    url: "/",
    tags: ["auto"],
    rating: 4.0,
    views: 100,
    id: 217,
    cards: ["Rose", "Cactus", "Cleo", "Green Rose", "Pink Rose"],
  },
  {
    name: "Toys",
    id: 43,
    url: "/",
    tags: ["Children", "Games"],
    rating: 4.5,
    views: 43,
    cards: ["Cards", "Car", "Ball", "Wheel", "LEGO"],
  },
  {
    id: 13,
    name: "Films",
    url: "/",
    tags: ["Actors", "Games"],
    rating: 4.5,
    views: 43,
    cards: ["Matrix", "Westwood", "Inception", "Wicked Games", "Avatar"],
  },
  {
    name: "Actors",
    id: 17,
    url: "/",
    tags: ["Films", "TV-shows"],
    rating: 4.5,
    views: 43,
    cards: ["Dicaprio", "Matt Damon", "Johny", "Wheel", "LEGO"],
  },
  {
    id: 771,
    name: "Flowers",
    url: "/",
    tags: ["auto"],
    rating: 4.0,
    views: 100,
    cards: ["Rose", "Cactus", "Cleo", "Green Rose", "Pink Rose"],
  },
  {
    name: "Toys",
    url: "/",
    tags: ["Children", "Games"],
    rating: 4.5,
    views: 43,
    id: 77,
    cards: ["Cards", "Car", "Ball", "Wheel", "LEGO"],
  },
  {
    name: "Films",
    url: "/",
    tags: ["Actors", "Games"],
    rating: 4.5,
    views: 43,
    id: 79,
    cards: ["Matrix", "Westwood", "Inception", "Wicked Games", "Avatar"],
  },
  {
    name: "Actors",
    url: "/",
    tags: ["Films", "TV-shows"],
    id: 1112,
    rating: 4.5,
    views: 43,
    cards: ["Dicaprio", "Matt Damon", "Johny", "Wheel", "LEGO"],
  },
  {
    name: "Flowers",
    url: "/",
    tags: ["auto"],
    rating: 4.0,
    id: 32,
    views: 100,
    cards: ["Rose", "Cactus", "Cleo", "Green Rose", "Pink Rose"],
  },
  {
    name: "Toys",
    url: "/",
    tags: ["Children", "Games"],
    rating: 4.5,
    id: 42,
    views: 43,
    cards: ["Cards", "Car", "Ball", "Wheel", "LEGO"],
  },
  {
    name: "Films",
    url: "/",
    tags: ["Actors", "Games"],
    rating: 4.5,
    id: 32,
    views: 43,
    cards: ["Matrix", "Westwood", "Inception", "Wicked Games", "Avatar"],
  },
  {
    name: "Actors",
    url: "/",
    tags: ["Films", "TV-shows"],
    rating: 4.5,
    id: 12,
    views: 43,
    cards: ["Dicaprio", "Matt Damon", "Johny", "Wheel", "LEGO"],
  },
  {
    name: "Flowers",
    url: "/",
    tags: ["auto"],
    rating: 4.0,
    id: 20,
    views: 100,
    cards: ["Rose", "Cactus", "Cleo", "Green Rose", "Pink Rose"],
  },
  {
    name: "Toys",
    url: "/",
    tags: ["Children", "Games"],
    rating: 4.5,
    id: 211,
    views: 43,
    cards: ["Cards", "Car", "Ball", "Wheel", "LEGO"],
  },
  {
    name: "Toys",
    url: "/",
    tags: ["Children", "Games"],
    rating: 4.5,
    id: 23,
    views: 43,
    cards: ["Cards", "Car", "Ball", "Wheel", "LEGO"],
  },
];

export default DECKS_MOCK;